version: "3"
services:
  postfix:
    build:
      context: ./postfix/
    container_name: postfix
    ports:
      - "25:25"
    environment:
      - DOMAIN=mail.thm64.com
      - SSL_CERT=/ssl/fullchain.cer
      - SSL_KEY=/ssl/*.thm64.com.key
    volumes:
      - /root/ssl/:/ssl
    restart: unless-stopped
